<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('items')->delete();
        
        \DB::table('items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'description' => NULL,
                'price' => 18,
                'name' => 'ÇOBAN SALATA',
                'img1' => 'images/meals/1705658787.png',
                'img2' => '',
                'img3' => '',
                'section_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2024-01-19 10:52:34',
            ),
            1 => 
            array (
                'id' => 2,
                'description' => '',
                'price' => 19,
                'name' => 'RUS SALATASI',
                'img1' => 'images/meals/Layer 82 copy.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2023-03-05 16:14:51',
            ),
            2 => 
            array (
                'id' => 3,
                'description' => '',
                'price' => 15,
                'name' => 'ACILI EZME',
                'img1' => 'images/meals/Layer 82.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'description' => NULL,
                'price' => 45,
                'name' => 'TAM EKMEK ET DÖNER',
                'img1' => 'images/meals/Layer 9.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 2,
                'created_at' => NULL,
                'updated_at' => '2024-01-17 19:03:16',
            ),
            4 => 
            array (
                'id' => 6,
                'description' => NULL,
                'price' => 35,
                'name' => 'ATOM EKMEK ET DÖNER',
                'img1' => 'images/meals/Layer 7.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 2,
                'created_at' => NULL,
                'updated_at' => '2024-01-17 18:58:43',
            ),
            5 => 
            array (
                'id' => 7,
                'description' => '',
                'price' => 75,
                'name' => 'PİLAV ÜSTÜ ET DÖNER',
                'img1' => 'images/meals/Layer 13.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'description' => '',
                'price' => 35,
                'name' => 'DÜRÜM ET DÖNER',
                'img1' => 'images/meals/Layer 10.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'description' => '',
                'price' => 75,
                'name' => 'BURSA KEBABE',
                'img1' => 'images/meals/Layer 12.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'description' => '',
                'price' => 70,
                'name' => 'PORSİYON ET DÖNER',
                'img1' => 'images/meals/Layer 14.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'description' => '',
                'price' => 65,
                'name' => 'PİDELİ KÖFTE',
                'img1' => 'images/meals/pidelikofte.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'description' => '',
                'price' => 65,
                'name' => 'PÖRSİYON KÖFTE',
                'img1' => 'images/meals/Layer 15.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'description' => '',
                'price' => 45,
                'name' => 'TAM EKMEK KÖFTE',
                'img1' => 'images/meals/Layer 16.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'description' => '',
                'price' => 35,
                'name' => 'ATOM EKMEK KÖFTE',
                'img1' => 'images/meals/Layer 17.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 15,
                'description' => '',
                'price' => 45,
                'name' => 'TAM EKMEK KUMRU',
                'img1' => 'images/meals/Layer 19.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 16,
                'description' => '',
                'price' => 35,
                'name' => 'ATOM EKMEK KUMRU',
                'img1' => 'images/meals/Layer 19 copy.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 17,
                'description' => '',
                'price' => 30,
                'name' => 'TAM EKMEK PATATES',
                'img1' => 'images/meals/Layer 20.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 18,
                'description' => '',
                'price' => 20,
                'name' => 'ATOM EKMEK PATATES',
                'img1' => 'images/meals/Layer 20 copy.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 19,
                'description' => '',
                'price' => 35,
                'name' => 'TAM EKMEK TAVUK DÖNER',
                'img1' => 'images/meals/TAMTAVUK.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 20,
                'description' => '',
                'price' => 30,
                'name' => 'İŞKEMBE ÇORBASI',
                'img1' => 'images/meals/Layer 59.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 21,
                'description' => '',
                'price' => 30,
                'name' => 'KELIE PAÇA ÇORBASI',
                'img1' => 'images/meals/Layer 61.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 22,
                'description' => '',
                'price' => 15,
                'name' => 'SÜTLAÇ ',
                'img1' => 'images/meals/sutlac.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 23,
                'description' => '',
                'price' => 15,
                'name' => 'KAZAN DİBİ',
                'img1' => 'images/meals/kazanDibi.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 24,
                'description' => '',
                'price' => 15,
                'name' => 'SUPANGELE',
                'img1' => 'images/meals/supangle.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 25,
                'description' => '',
                'price' => 12,
                'name' => 'FANTA',
                'img1' => 'images/meals/fanta.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 26,
                'description' => '',
                'price' => 12,
                'name' => 'COCACOLA',
                'img1' => 'images/meals/kola.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 27,
                'description' => '',
                'price' => 12,
                'name' => 'cocacola zero ',
                'img1' => 'images/meals/zero.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 28,
                'description' => '',
                'price' => 12,
                'name' => 'fanta Şişe',
                'img1' => 'images/meals/fanta s.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 29,
                'description' => '',
                'price' => 12,
                'name' => 'CocaCola Şişe',
                'img1' => 'images/meals/kola s.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 30,
                'description' => '',
                'price' => 12,
                'name' => 'Acılı Şalgam',
                'img1' => 'images/meals/slagam.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 31,
                'description' => '',
                'price' => 12,
                'name' => 'Acısız Şaglam',
                'img1' => 'images/meals/salgam2.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 32,
                'description' => '',
                'price' => 4,
                'name' => 'Çay',
                'img1' => 'images/meals/cay-cay-bardagi-kahvalti-cay-simit-incebelli-bardak-resimleri.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 33,
                'description' => '',
                'price' => 4,
                'name' => 'Su',
                'img1' => 'images/meals/petsu3.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 34,
                'description' => '',
                'price' => 9,
                'name' => 'Ayran Büyük',
                'img1' => 'images/meals/Layer 1.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 35,
                'description' => '',
                'price' => 6,
                'name' => 'Ayran Küçük',
                'img1' => 'images/meals/Kayran.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 36,
                'description' => '',
                'price' => 7,
                'name' => 'Sade Soda',
                'img1' => 'images/meals/sade soda.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 37,
                'description' => '',
                'price' => 210,
                'name' => 'Meyveli Soda',
                'img1' => 'images/meals/elmali soda.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 12,
                'created_at' => NULL,
                'updated_at' => '2023-03-06 13:36:35',
            ),
            36 => 
            array (
                'id' => 38,
                'description' => '',
                'price' => 77,
                'name' => 'HAMBURGER + PATATES + AYRAN',
                'img1' => 'images/meals/Layer 50.png',
                'img2' => 'images/meals/Layer 41.png',
                'img3' => 'images/meals/Kayran.png',
                'section_id' => 13,
                'created_at' => NULL,
                'updated_at' => '2023-03-05 16:08:56',
            ),
            37 => 
            array (
                'id' => 39,
                'description' => '',
                'price' => 77,
                'name' => 'PİDELİ KÖFTE + TATLE + KOLA',
                'img1' => 'images/meals/pidelikofte.png',
                'img2' => 'images/meals/EKER.png
',
                'img3' => 'images/meals/kola.png',
                'section_id' => 13,
                'created_at' => NULL,
                'updated_at' => '2023-03-05 16:08:56',
            ),
            38 => 
            array (
                'id' => 42,
                'description' => '',
                'price' => 77,
                'name' => 'PİLİÇ ŞİNİTZEL + PATATES + AYRAN',
                'img1' => 'images/meals/Layer 14.png',
                'img2' => 'images/meals/Layer 41.png',
                'img3' => 'images/meals/Kayran.png',
                'section_id' => 13,
                'created_at' => NULL,
                'updated_at' => '2023-03-05 16:08:56',
            ),
            39 => 
            array (
                'id' => 43,
                'description' => '',
                'price' => 60,
                'name' => 'SOĞUK SANDVİÇ + PATATES + AYRAN',
                'img1' => 'images/meals/Layer 17.png',
                'img2' => 'images/meals/Layer 41.png',
                'img3' => 'images/meals/Kayran.png',
                'section_id' => 13,
                'created_at' => NULL,
                'updated_at' => '2023-03-06 13:36:34',
            ),
            40 => 
            array (
                'id' => 44,
                'description' => '',
                'price' => 110,
                'name' => 'ATOM KUMRU + PATATES + AYRAN',
                'img1' => 'images/meals/Layer 19.png',
                'img2' => 'images/meals/Layer 41.png',
                'img3' => 'images/meals/Kayran.png',
                'section_id' => 13,
                'created_at' => NULL,
                'updated_at' => '2023-03-06 13:36:34',
            ),
            41 => 
            array (
                'id' => 45,
                'description' => '',
                'price' => 50,
                'name' => 'ATOM ET + PATATES + AYRAN',
                'img1' => 'images/meals/Layer 7.png',
                'img2' => 'images/meals/Layer 41.png',
                'img3' => 'images/meals/Kayran.png',
                'section_id' => 13,
                'created_at' => NULL,
                'updated_at' => '2023-03-06 13:36:34',
            ),
            42 => 
            array (
                'id' => 46,
                'description' => '',
                'price' => 2,
                'name' => 'TAM ET + PATATES + AYRAN',
                'img1' => 'images/meals/Layer 9.png',
                'img2' => 'images/meals/Layer 41.png',
                'img3' => 'images/meals/Kayran.png',
                'section_id' => 13,
                'created_at' => NULL,
                'updated_at' => '2023-03-05 16:08:56',
            ),
            43 => 
            array (
                'id' => 47,
                'description' => '',
                'price' => 3,
                'name' => 'DÜRÜNM ET + PATATES + AYRAN',
                'img1' => 'images/meals/Layer 10.png',
                'img2' => 'images/meals/Layer 41.png',
                'img3' => 'images/meals/Kayran.png',
                'section_id' => 13,
                'created_at' => NULL,
                'updated_at' => '2023-03-05 16:08:56',
            ),
            44 => 
            array (
                'id' => 48,
                'description' => '',
                'price' => 4,
                'name' => 'BURSA KEBABI + TATLI + KOLA',
                'img1' => 'images/meals/Layer 12.png',
                'img2' => 'images/meals/EKER.png
',
                'img3' => 'images/meals/kola.png',
                'section_id' => 13,
                'created_at' => NULL,
                'updated_at' => '2023-03-05 16:08:56',
            ),
            45 => 
            array (
                'id' => 49,
                'description' => '',
                'price' => 77,
                'name' => 'ATOM TAVUK + PATATES + AYRAN',
                'img1' => 'images/meals/Layer 22.png',
                'img2' => 'images/meals/Layer 41.png',
                'img3' => 'images/meals/Kayran.png',
                'section_id' => 13,
                'created_at' => NULL,
                'updated_at' => '2023-03-05 16:08:56',
            ),
            46 => 
            array (
                'id' => 50,
                'description' => '',
                'price' => 77,
                'name' => 'TAM TAVUK + PATATES + AYRAN',
                'img1' => 'images/meals/TAMTAVUK.png',
                'img2' => 'images/meals/Layer 41.png',
                'img3' => 'images/meals/Kayran.png',
                'section_id' => 13,
                'created_at' => NULL,
                'updated_at' => '2023-03-05 09:29:05',
            ),
            47 => 
            array (
                'id' => 51,
                'description' => '',
                'price' => 77,
                'name' => 'DÜRÜM TAVUK + PATATES + AYRAN',
                'img1' => 'images/meals/Layer 33.png',
                'img2' => 'images/meals/Layer 41.png',
                'img3' => 'images/meals/Kayran.png',
                'section_id' => 13,
                'created_at' => NULL,
                'updated_at' => '2023-03-05 16:08:56',
            ),
            48 => 
            array (
                'id' => 52,
                'description' => '',
                'price' => 25,
                'name' => 'ATOM EKMEK TAVUK DÖNER',
                'img1' => 'images/meals/Layer 22.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 53,
                'description' => '',
                'price' => 65,
                'name' => 'PİLAV ÜSTÜ TAVUK DÖNER',
                'img1' => 'images/meals/Layer 31.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 54,
                'description' => '',
                'price' => 25,
                'name' => 'DÜRÜM TAVUK DÖNER',
                'img1' => 'images/meals/Layer 33.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 55,
                'description' => '',
                'price' => 60,
                'name' => 'TAVUK KEBABI',
                'img1' => 'images/meals/Layer 34.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 56,
                'description' => '',
                'price' => 60,
                'name' => 'PORSİYON TAVUK DÖNER',
                'img1' => 'images/meals/Layer 35.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 57,
                'description' => '',
                'price' => 25,
                'name' => 'KAŞARLI TOST',
                'img1' => 'images/meals/Layer 37.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 58,
                'description' => '',
                'price' => 25,
                'name' => 'SUCUKLU TOST',
                'img1' => 'images/meals/Layer 38.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 59,
                'description' => '',
                'price' => 25,
                'name' => 'KARIŞIK TOST',
                'img1' => 'images/meals/Layer 39.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 60,
                'description' => '',
                'price' => 35,
                'name' => 'DUBLE KARIŞIK TOST',
                'img1' => 'images/meals/Layer 40.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 61,
                'description' => '',
                'price' => 20,
                'name' => 'PARMAK PATATES',
                'img1' => 'images/meals/Layer 41.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 62,
                'description' => '',
                'price' => 25,
                'name' => 'ELMA DİLİM PATATES ',
                'img1' => 'images/meals/Layer 43.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 63,
                'description' => '',
                'price' => 25,
                'name' => 'SOĞAN HALKASI',
                'img1' => 'images/meals/Layer 48.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 64,
                'description' => '',
                'price' => 25,
                'name' => 'SİGARA BÖREĞİ',
                'img1' => 'images/meals/Layer 46.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 65,
                'description' => '',
                'price' => 25,
                'name' => 'HAMBURGER',
                'img1' => 'images/meals/Layer 50.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 66,
                'description' => '',
                'price' => 25,
                'name' => 'PİLİÇ BURGER',
                'img1' => 'images/meals/tavukburger.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 67,
                'description' => '',
                'price' => 35,
                'name' => 'ATOM PİLİÇ ŞİNİTZEL',
                'img1' => 'images/meals/pş.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 68,
                'description' => '',
                'price' => 35,
                'name' => 'DUBLE BURGER',
                'img1' => 'images/meals/Layer 54.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 69,
                'description' => '',
                'price' => 20,
                'name' => 'MERCİMEK ÇORBASI',
                'img1' => 'images/meals/Layer 55.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 70,
                'description' => '',
                'price' => 20,
                'name' => 'TAVUK SUYU ÇORBASI',
                'img1' => 'images/meals/Layer 57.png',
                'img2' => NULL,
                'img3' => NULL,
                'section_id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}